### PR TITLE
Update apt repository key checksums

### LINKED ISSUE #140: Default apt key checksum mismatch
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
- Ruby:
- Distribution: Debian 11
- Module version: 4.0.2

## What are you seeing
```
Failure when trying to do a puppet run using this module:
[exec] Error: File written to disk did not match desired checksum; discarding changes ({sha256}4f9e668fbdaaedf4fc8d83f4eb98db33553d7f4e1f0bca212d0a7ccc9f1a6adf vs {sha256}2e532e3f800b788b0248da86b1cd722e58e9c99413912fd029c20d88d55ebadc)
[exec] Error: /Stage[main]/Lldpd/File[/usr/share/keyrings/lldpd.asc]/ensure: change from 'absent' to 'file' failed: File written to disk did not match desired checksum; discarding changes ({sha256}4f9e668fbdaaedf4fc8d83f4eb98db33553d7f4e1f0bca212d0a7ccc9f1a6adf vs {sha256}2e532e3f800b788b0248da86b1cd722e58e9c99413912fd029c20d88d55ebadc)
```

## Any additional information you'd like to impart
Minor problem since it's easy to work around in hiera.

Interestingly:
```
$ curl -s https://download.opensuse.org/repositories/home:/vbernat/Debian_11/Release.key | sha256sum
4f9e668fbdaaedf4fc8d83f4eb98db33553d7f4e1f0bca212d0a7ccc9f1a6adf  -
$ curl -s https://download.opensuse.org/repositories/home:/vbernat/xUbuntu_22.04/Release.key | sha256sum
2e532e3f800b788b0248da86b1cd722e58e9c99413912fd029c20d88d55ebadc  -
```
So (at least right now) different keys are used to sign the packages for different distributions.

### PR DESCRIPTION
**Pull request by b4ldr**
~~The key file used for debian-11 is different then the default one.~~

The previous apt key has expired and the key was replaced by a new one for which the checksum needs to be updated.

Fixes #140

### CODE REVIEW

**Comment by smortex** [comment]
Fixed typo and rebased on top of WIP.

It looks like the previous key has expired and a new one was only installed on the Debian 11 / Ubuntu 22.04 repos. Fun fact, on Debian 9 and Ubuntu 16.04 apt does not care about the key expiration date so the test suite pass there :upside_down_face:.

@b4ldr do you have a way to contact vbernat who manage the repo this module get packages from?

**Comment by smortex** [comment]
Fixed typo and rebased on top of current WIP.

Cc @vincentbernat who manage the repo we get lldp packages from:

It looks like the previous key has expired and a new one was only installed on the Debian 11 / Ubuntu 22.04 repos, but not on the older releases repos (yet, the last modification date of the `Release.key` files is recent, maybe the old key was reuploaded in place?). Fun fact, on Debian 9 and Ubuntu 16.04 apt does not care about the key expiration date so the test suite pass there :upside_down_face:.

@vincentbernat where can we report such issues?  Can you please have a look to the keys used to sign the lldp repos to ensure the key is not expired?

Thanks!

**Comment by vincentbernat** [comment]
I'll do a dummy upload to check if it is enough to regenerate the key.

**Comment by vincentbernat** [comment]
Could you trigger the tests again to check if the problem is now fixed?

**Comment by smortex** [comment]
Thanks @vincentbernat !  That seems to fix the root cause.  The failure we see now are expected as the key change needs us to update the file checksums accordingly :wink:   Thanks a lot!

**Comment by smortex** [comment]
Awesome, this now pass everywhere thanks to the fast fix from @vincentbernat !

@b4ldr I re-wrote the commit now that the updated key is used on all repos and updated the PR accordingly.  I think this should be considered a backward incompatible change since we change the default value of a parameter?

**Review by bastelfreak — APPROVED** [review]

**Pull request merged**
